name: Flutter CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - name: Flutter action
      uses: subosito/flutter-action@v1.3.2
      with:
        # The Flutter version to make available on the path
        flutter-version: 1.17.0
        # The Flutter build release channel
        channel: stable
    - run: flutter pub get
    - run: flutter test
    - run: flutter build apk
